In [1]:
import torch

파이토치 텐서 생성하기

In [2]:
ft = torch.FloatTensor([[1,2],[3,4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [3]:
lt = torch.LongTensor([[1,2],[3,4]])
bt = torch.ByteTensor([[1,0],[0,1]])

넘파이 호환

In [4]:
import numpy as np

x= np.array([[1,2],[3,4]])
print(x,type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [5]:
x = torch.from_numpy(x)
print(x, type(x))

tensor([[1, 2],
        [3, 4]], dtype=torch.int32) <class 'torch.Tensor'>


텐서 타입 변환

In [6]:
ft.long()
lt.float()

tensor([[1., 2.],
        [3., 4.]])

텐서 크기 구하기

In [7]:
x= torch.FloatTensor([[[1,2],
     [3,4]],
    [[5,6],
     [7,8]],
    [[9,10],
     [11,12]]])
print(x.size())

torch.Size([3, 2, 2])


In [8]:
print(x)

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])


실습 - 기본연산

In [9]:
a = torch.FloatTensor([[1,2],[3,4]])
b = torch.FloatTensor([[2,2],[3,3]])
print(a)
print(b)

tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 2.],
        [3., 3.]])


In [10]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

tensor([[3., 4.],
        [6., 7.]])
tensor([[-1.,  0.],
        [ 0.,  1.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])


In [11]:
print(a**b)

tensor([[ 1.,  4.],
        [27., 64.]])


In [12]:
print(a==b)

tensor([[False,  True],
        [ True, False]])


In [13]:
print(a!=b)

tensor([[ True, False],
        [False,  True]])


실습 - 인플레이스 연산

In [14]:
print(a)

tensor([[1., 2.],
        [3., 4.]])


In [15]:
print(a.mul(b))

tensor([[ 2.,  4.],
        [ 9., 12.]])


In [16]:
print(a)

tensor([[1., 2.],
        [3., 4.]])


In [17]:
print(a.mul_(b))

tensor([[ 2.,  4.],
        [ 9., 12.]])


In [18]:
print(a)

tensor([[ 2.,  4.],
        [ 9., 12.]])


실습 - 차원 축소 연산 : 합과 평균

In [19]:
x = torch.FloatTensor([[1,2],[3,4]])
x

tensor([[1., 2.],
        [3., 4.]])

In [20]:
print(x.sum())
print(x.mean())

tensor(10.)
tensor(2.5000)


In [21]:
print(x.sum(dim=0)) #dim:차원 #dim=0 => 첫번째 차원 즉, 세로축에 대해하여 합 연산

tensor([4., 6.])


In [22]:
print(x.sum(dim=-1)) #dim=-1 2차원

tensor([3., 7.])


실습 - 브로드캐스트 연산

In [23]:
x = torch.FloatTensor([[1,2],[3,4]])
y = 1

In [24]:
z = x+y
print(z)
print(z.size())

tensor([[2., 3.],
        [4., 5.]])
torch.Size([2, 2])


In [25]:
x = torch.FloatTensor([[1,2],[4,8]])
y = torch.FloatTensor([3,5])
print(x.size())
print(y.size())
z = x+y
print(z)
print(z.size())

torch.Size([2, 2])
torch.Size([2])
tensor([[ 4.,  7.],
        [ 7., 13.]])
torch.Size([2, 2])


In [26]:
x = torch.FloatTensor([[[1,2]]])
y = torch.FloatTensor([3,5])

print(x.size())
print(y.size())

torch.Size([1, 1, 2])
torch.Size([2])


In [27]:
z = x + y
print(z)
print(z.size())

tensor([[[4., 7.]]])
torch.Size([1, 1, 2])


In [28]:
x = torch.FloatTensor([[1,2]])
y = torch.FloatTensor([[3],[5]])
print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([2, 1])


In [29]:
z= x+y
print(z)
print(z.size())

tensor([[4., 5.],
        [6., 7.]])
torch.Size([2, 2])


실습 - 텐서 형태 변환

1) View 함수

In [30]:
x = torch.FloatTensor([[[1,2],
                        [3,4]],
                        [[5,6],
                        [7,8]],
                        [[9,10],
                        [11,12]]])
print(x.size())

torch.Size([3, 2, 2])


In [31]:
print(x.view(12))
print(x.view(3,4))
print(x.view(3,1,4))

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


In [32]:
print(x.view(-1))
print(x.view(3,-1))
print(x.view(-1,1,4))

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


In [33]:
y = x.view(3,4)
x.storage().data_ptr() == y.storage().data_ptr()

C:\Users\admin\AppData\Local\Temp\ipykernel_8448\2969183149.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  x.storage().data_ptr() == y.storage().data_ptr()


True

In [34]:
print(x.reshape(3,4))

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


2) Squeeze 함수 : 차원의 크기가 1인 차원을 없애줌

In [35]:
x = torch.FloatTensor([[[1,2],
                        [3,4]]])

print(x.size())

torch.Size([1, 2, 2])


In [36]:
print(x.squeeze())
print(x.squeeze().size())

tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])


In [37]:
print(x.squeeze(0).size())
print(x.squeeze(1).size())

torch.Size([2, 2])
torch.Size([1, 2, 2])


3) Unsqueeze 함수 : squeeze의 반대 역할. 지정된 차원의 인덱스에 차원의 크기가 1인 차원을 삽입

In [39]:
x= torch.FloatTensor([[1,2],[3,4]])
print(x.size())

torch.Size([2, 2])


In [42]:
print(x.unsqueeze(1).size())
print(x.unsqueeze(-1).size())
print(x.unsqueeze(2).size())

torch.Size([2, 1, 2])
torch.Size([2, 2, 1])
torch.Size([2, 2, 1])


In [43]:
print(x.reshape(2,2,-1).size())

torch.Size([2, 2, 1])


실습 - 텐서 자르기 & 붙이기