In [33]:
import torch

파이토치 텐서 생성하기

In [34]:
ft = torch.FloatTensor([[1,2],[3,4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [35]:
lt = torch.LongTensor([[1,2],[3,4]])
bt = torch.ByteTensor([[1,0],[0,1]])

넘파이 호환

In [36]:
import numpy as np

x= np.array([[1,2],[3,4]])
print(x,type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [37]:
x = torch.from_numpy(x)
print(x, type(x))

tensor([[1, 2],
        [3, 4]], dtype=torch.int32) <class 'torch.Tensor'>


텐서 타입 변환

In [38]:
ft.long()
lt.float()

tensor([[1., 2.],
        [3., 4.]])

텐서 크기 구하기

In [39]:
x= torch.FloatTensor([[[1,2],
     [3,4]],
    [[5,6],
     [7,8]],
    [[9,10],
     [11,12]]])
print(x.size())

torch.Size([3, 2, 2])


In [40]:
print(x)

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])


실습 - 기본연산

In [41]:
a = torch.FloatTensor([[1,2],[3,4]])
b = torch.FloatTensor([[2,2],[3,3]])
print(a)
print(b)

tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 2.],
        [3., 3.]])


In [42]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

tensor([[3., 4.],
        [6., 7.]])
tensor([[-1.,  0.],
        [ 0.,  1.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])


In [43]:
print(a**b)

tensor([[ 1.,  4.],
        [27., 64.]])


In [44]:
print(a==b)

tensor([[False,  True],
        [ True, False]])


In [45]:
print(a!=b)

tensor([[ True, False],
        [False,  True]])


실습 - 인플레이스 연산

In [46]:
print(a)

tensor([[1., 2.],
        [3., 4.]])


In [47]:
print(a.mul(b))

tensor([[ 2.,  4.],
        [ 9., 12.]])


In [48]:
print(a)

tensor([[1., 2.],
        [3., 4.]])


In [49]:
print(a.mul_(b))

tensor([[ 2.,  4.],
        [ 9., 12.]])


In [50]:
print(a)

tensor([[ 2.,  4.],
        [ 9., 12.]])


실습 - 차원 축소 연산 : 합과 평균

In [51]:
x = torch.FloatTensor([[1,2],[3,4]])
x

tensor([[1., 2.],
        [3., 4.]])

In [52]:
print(x.sum())
print(x.mean())

tensor(10.)
tensor(2.5000)


In [53]:
print(x.sum(dim=0)) #dim:차원 #dim=0 => 첫번째 차원 즉, 세로축에 대해하여 합 연산

tensor([4., 6.])


In [54]:
print(x.sum(dim=-1)) #dim=-1 2차원

tensor([3., 7.])


실습 - 브로드캐스트 연산

In [55]:
x = torch.FloatTensor([[1,2],[3,4]])
y = 1

In [56]:
z = x+y
print(z)
print(z.size())

tensor([[2., 3.],
        [4., 5.]])
torch.Size([2, 2])


In [57]:
x = torch.FloatTensor([[1,2],[4,8]])
y = torch.FloatTensor([3,5])
print(x.size())
print(y.size())
z = x+y
print(z)
print(z.size())

torch.Size([2, 2])
torch.Size([2])
tensor([[ 4.,  7.],
        [ 7., 13.]])
torch.Size([2, 2])


In [58]:
x = torch.FloatTensor([[[1,2]]])
y = torch.FloatTensor([3,5])

print(x.size())
print(y.size())

torch.Size([1, 1, 2])
torch.Size([2])


In [59]:
z = x + y
print(z)
print(z.size())

tensor([[[4., 7.]]])
torch.Size([1, 1, 2])


In [60]:
x = torch.FloatTensor([[1,2]])
y = torch.FloatTensor([[3],[5]])
print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([2, 1])


In [61]:
z= x+y
print(z)
print(z.size())

tensor([[4., 5.],
        [6., 7.]])
torch.Size([2, 2])


실습 - 텐서 형태 변환

1) View 함수

In [63]:
x = torch.FloatTensor([[[1,2],
                        [3,4]],
                        [[5,6],
                        [7,8]],
                        [[9,10],
                        [11,12]]])
print(x.size())

torch.Size([3, 2, 2])


In [66]:
print(x.view(12))
print(x.view(3,4))
print(x.view(3,1,4))

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
